name: easy_pdf_viewer_example
description: Demonstrates how to use the easy_pdf_viewer plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  easy_pdf_viewer:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/sample.pdf
    - assets/sample2.pdf
