name: easy_pdf_viewer
version: 1.1.1
homepage: https://github.com/SunnatilloShavkatov/easy_pdf_viewer.git
description: "A flutter plugin for handling PDF files. Works on both Android & iOS"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.2

flutter:
  plugin:
    platforms:
      android:
        package: dev.kaichi.easy_pdf_viewer
        pluginClass: EasyPdfViewerPlugin
      ios:
        pluginClass: EasyPdfViewerPlugin
