name: easy_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.8
homepage: https://github.com/SunnatilloShavkatov/easy_pdf_viewer.git

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: dev.kaichi.easy_pdf_viewer
        pluginClass: EasyPdfViewerPlugin
      ios:
        pluginClass: EasyPdfViewerPlugin
